- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: "/home/ubuntu/.ssh/{{item.app_name}}"
    comment: "{{email}}"
    force: yes
    mode: "400"
    owner: ubuntu
  loop: "{{repos}}"
  
- name: fetch ssh key
  fetch:
      src: "/home/ubuntu/.ssh/{{item.app_name}}.pub"
      dest: "./key/{{item.app_name}}.pub"
      flat: yes
  loop: "{{repos}}"

- name: Add a new read-only deploy key to a GitHub repository using basic authentication
  community.general.github_deploy_key:
    owner: "{{item.repo_own}}"
    repository: "{{item.repo}}"
    name: "{{item.app_name}}"
    key: "{{ lookup('file', './key/{{item.app_name}}.pub') }}"
    read_only: yes
    force: yes
    token: "{{github_token}}"
  loop: "{{repos}}"
  